[build-system]
requires = ["maturin>=1.0,<2.0"]
build-backend = "maturin"

[project]
name = "frost_rs"
requires-python = ">=3.7, < 3.13"
classifiers = [
    "Programming Language :: Rust",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
readme = "README.md"
dynamic = ["version"]
[tool.maturin]
features = ["pyo3/extension-module"]
module-name = "frost"
python-source = "python"
strip = true
